#!/bin/bash
# Provision the voice-agent VM (Ubuntu 24.04) as Jett's inbound voice proxy.
# Run as root (or with sudo). Idempotent: safe to re-run.
#
# Stack:
#   livekit-server  (SFU, localhost signaling)
#   livekit-sip     (SIP <-> WebRTC bridge, public SIP on :5060)
#   redis-server    (shared bus for the above)
#   python venv: livekit-agents, livekit-api, faster-whisper (tiny.en),
#                kokoro-onnx (no torch — onnxruntime only)
#   systemd units: livekit-server, livekit-sip, jett-proxy (the voice worker)
#
# No local LLM anywhere: the brain is OpenRouter (model meta/muse-spark-1.3;
# key arrives later as OPENROUTER_API_KEY, Meta direct as optional fallback).
# 1 GB RAM budget.
set -euo pipefail

AGENT_DIR=/opt/agent
SERVICE_USER=agent
SERVICE_HOME=/home/agent
PUBLIC_IP=129.159.189.244

echo "== swap (2G, small box insurance) =="
if [ ! -f /swapfile ]; then
  fallocate -l 2G /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=2048 status=none
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo "/swapfile none swap sw 0 0" >> /etc/fstab
fi
echo OK

echo "== system packages =="
# Wait out any concurrent apt holder (unattended-upgrades, or a duplicate
# deploy racing us) instead of dying on the lock.
for i in $(seq 1 30); do
  if ! fuser /var/lib/apt/lists/lock >/dev/null 2>&1 \
     && ! fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; then
    break
  fi
  echo "apt lock held, waiting ${i}/30..."
  sleep 10
done
apt-get update -qq
apt-get install -y -qq python3-venv python3-dev ffmpeg espeak-ng \
    build-essential cmake curl git redis-server openssl \
    pkg-config libopus-dev libopusfile-dev libsoxr-dev > /dev/null
# redis: local bus only
sed -i 's/^supervised .*/supervised systemd/' /etc/redis/redis.conf 2>/dev/null || true
systemctl enable --now redis-server
echo OK

id -u $SERVICE_USER >/dev/null 2>&1 || useradd -m -s /bin/bash $SERVICE_USER
mkdir -p $AGENT_DIR
chown -R $SERVICE_USER:$SERVICE_USER $AGENT_DIR
# agent's ssh dir (bus repo deploy key lives here)
sudo -u $SERVICE_USER mkdir -p $SERVICE_HOME/.ssh
chmod 700 $SERVICE_HOME/.ssh

echo "== livekit-server binary =="
if [ ! -x $AGENT_DIR/bin/livekit-server ]; then
  mkdir -p $AGENT_DIR/bin
  LK_TAG=$(curl -fsSL https://api.github.com/repos/livekit/livekit/releases/latest | grep -o '"tag_name": *"[^"]*"' | head -1 | cut -d'"' -f4)
  echo "livekit-server tag: $LK_TAG"
  ASSET_URL=$(curl -fsSL "https://api.github.com/repos/livekit/livekit/releases/tags/$LK_TAG" | grep -o '"browser_download_url": *"[^"]*linux_amd64\.tar\.gz"' | head -1 | cut -d'"' -f4)
  curl -fsSL --retry 3 "$ASSET_URL" -o /tmp/lk.tgz
  tar xzf /tmp/lk.tgz -C $AGENT_DIR/bin livekit-server
  chmod +x $AGENT_DIR/bin/livekit-server
  rm -f /tmp/lk.tgz
fi
$AGENT_DIR/bin/livekit-server --version 2>&1 | head -1 || true
echo OK

echo "== livekit-sip (build from source; no release binaries published) =="
if [ ! -x $AGENT_DIR/bin/livekit-sip ]; then
  mkdir -p $AGENT_DIR/bin
  if ! command -v go >/dev/null 2>&1; then
    echo "-- installing go toolchain --"
    GO_TAR=$(curl -fsSL https://go.dev/dl/?mode=json | grep -o '"filename": *"go[0-9.]*\.linux-amd64\.tar\.gz"' | head -1 | cut -d'"' -f4)
    echo "go tarball: $GO_TAR"
    curl -fsSL --retry 3 "https://go.dev/dl/$GO_TAR" -o /tmp/go.tgz
    rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go.tgz
    rm -f /tmp/go.tgz
  fi
  export PATH=$PATH:/usr/local/go/bin
  go version
  echo "-- cloning livekit/sip --"
  rm -rf /tmp/sip-src
  git clone --depth 1 https://github.com/livekit/sip.git /tmp/sip-src
  echo "-- building (CGO, low parallelism for 1GB box) --"
  cd /tmp/sip-src
  CGO_ENABLED=1 GOFLAGS=-p=2 GOMAXPROCS=1 go build -trimpath -o $AGENT_DIR/bin/livekit-sip ./cmd/livekit-sip
  cd /
  rm -rf /tmp/sip-src
  chmod +x $AGENT_DIR/bin/livekit-sip
fi
$AGENT_DIR/bin/livekit-sip --help 2>&1 | head -2 || true
echo OK

echo "== livekit api key/secret (server-side only, never printed) =="
LK_ENV=$AGENT_DIR/livekit.env
if [ ! -f $LK_ENV ]; then
  LK_KEY="devkey_$(openssl rand -hex 8)"
  LK_SECRET="$(openssl rand -hex 32)"
  printf 'LIVEKIT_API_KEY=%s\nLIVEKIT_API_SECRET=%s\n' "$LK_KEY" "$LK_SECRET" > $LK_ENV
  chmod 600 $LK_ENV
  chown $SERVICE_USER:$SERVICE_USER $LK_ENV
  echo "generated (stored in $LK_ENV)"
else
  echo "exists, kept"
fi

echo "== livekit-server config =="
cat > $AGENT_DIR/livekit.yaml <<EOF
# generated by setup.sh — do not edit by hand
port: 7880
bind_addresses:
  - "0.0.0.0"
rtc:
  use_external_ip: true
  tcp_port: 7881
  udp_port: 7882
redis:
  address: localhost:6379
room:
  auto_create: true
  empty_timeout: 300
keys:
  __LK_KEY__: __LK_SECRET__
logging:
  level: info
EOF
# inject key/secret without ever printing them
LK_KEY_V=$(grep ^LIVEKIT_API_KEY= $LK_ENV | cut -d= -f2)
LK_SECRET_V=$(grep ^LIVEKIT_API_SECRET= $LK_ENV | cut -d= -f2)
sed -i "s/__LK_KEY__/$LK_KEY_V/; s/__LK_SECRET__/$LK_SECRET_V/" $AGENT_DIR/livekit.yaml
chmod 600 $AGENT_DIR/livekit.yaml
chown $SERVICE_USER:$SERVICE_USER $AGENT_DIR/livekit.yaml
echo OK

echo "== livekit-sip config =="
cat > $AGENT_DIR/sip.yaml <<EOF
# generated by setup.sh — do not edit by hand
log_level: info
ws_url: ws://localhost:7880
redis:
  address: localhost:6379
sip_port: 5060
rtp_port: 12000-12100
use_external_ip: true
EOF
chmod 600 $AGENT_DIR/sip.yaml
chown $SERVICE_USER:$SERVICE_USER $AGENT_DIR/sip.yaml
echo OK

echo "== python venv =="
if [ ! -x $AGENT_DIR/venv/bin/python ]; then
    python3 -m venv $AGENT_DIR/venv
fi
$AGENT_DIR/venv/bin/pip -q install --upgrade pip
$AGENT_DIR/venv/bin/pip -q install \
    livekit-agents livekit-api livekit-plugins-openai livekit-plugins-silero \
    faster-whisper onnxruntime \
    kokoro-onnx \
    soundfile numpy huggingface_hub
chown -R $SERVICE_USER:$SERVICE_USER $AGENT_DIR/venv
echo OK

echo "== whisper model (tiny.en, cached) =="
sudo -u $SERVICE_USER $AGENT_DIR/venv/bin/python -c "
from faster_whisper import WhisperModel
WhisperModel('tiny.en', device='cpu', compute_type='int8')
print('whisper cached')"
echo OK

echo "== kokoro-onnx model (downloaded now, ~115 MB) =="
sudo -u $SERVICE_USER mkdir -p /opt/agent/models
for f in kokoro-v1.0.int8.onnx voices-v1.0.bin; do
  if [ -s /opt/agent/models/$f ]; then echo "$f cached"; continue; fi
  sudo -u $SERVICE_USER curl -fL --retry 3 -o /opt/agent/models/$f \
    "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/$f"
done
sudo -u $SERVICE_USER $AGENT_DIR/venv/bin/python -c "
from kokoro_onnx import Kokoro
k = Kokoro('/opt/agent/models/kokoro-v1.0.int8.onnx',
           '/opt/agent/models/voices-v1.0.bin')
samples, sr = k.create('warmup check', voice='af_heart', speed=1.0, lang='en-us')
assert len(samples) > 1000 and sr == 24000, (len(samples), sr)
print('kokoro warmup OK', len(samples), 'samples @', sr)"
echo OK

echo "== bus repo deploy key (for agent-call-bus, generated once) =="
KEY=$SERVICE_HOME/.ssh/bus_key
if [ ! -f $KEY ]; then
  sudo -u $SERVICE_USER ssh-keygen -t ed25519 -N '' -f $KEY -C "jett-proxy-bus-key" -q
  echo "generated new deploy key"
else
  echo "exists, kept"
fi
echo "--- PUBLIC KEY (add as deploy key with WRITE access to intelogroup/agent-call-bus) ---"
cat $KEY.pub
echo "--- end public key ---"
# try a first clone; non-fatal if the deploy key isn't added yet
if [ ! -d $AGENT_DIR/bus/.git ]; then
  sudo -u $SERVICE_USER env GIT_SSH_COMMAND="ssh -i $KEY -o StrictHostKeyChecking=no" \
    git clone git@github.com:intelogroup/agent-call-bus.git $AGENT_DIR/bus 2>&1 | head -3 || echo "(bus clone deferred — add the deploy key, it retries on first consult)"
fi
echo OK

echo "== git identity for bus commits =="
sudo -u $SERVICE_USER git config --global user.email "jett-proxy@129.159.189.244" 2>/dev/null || true
sudo -u $SERVICE_USER git config --global user.name "jett-proxy" 2>/dev/null || true
echo OK

echo "== systemd units =="
cp $AGENT_DIR/jett-proxy.service /etc/systemd/system/jett-proxy.service
cat > /etc/systemd/system/livekit-server.service <<EOF
[Unit]
Description=LiveKit server (voice SFU)
After=network.target redis-server.service
Wants=redis-server.service

[Service]
User=$SERVICE_USER
EnvironmentFile=$AGENT_DIR/livekit.env
ExecStart=$AGENT_DIR/bin/livekit-server --config $AGENT_DIR/livekit.yaml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
cat > /etc/systemd/system/livekit-sip.service <<EOF
[Unit]
Description=LiveKit SIP bridge
After=network.target livekit-server.service
Wants=livekit-server.service

[Service]
User=$SERVICE_USER
EnvironmentFile=$AGENT_DIR/livekit.env
ExecStart=$AGENT_DIR/bin/livekit-sip --config $AGENT_DIR/sip.yaml
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable livekit-server livekit-sip jett-proxy.service redis-server
echo OK

echo
echo "DONE. Next: deploy workflow writes agent.env, creates the SIP trunk +"
echo "dispatch rule (setup-sip.py), and restarts everything."
