name: "(temporary) start oracle jett-proxy"
on:
  workflow_dispatch:
jobs:
  start:
    runs-on: [self-hosted, oracle]
    timeout-minutes: 5
    steps:
      - name: Start jett-proxy worker
        run: |
          set -x
          sudo systemctl start jett-proxy
          sleep 5
          systemctl is-active jett-proxy && echo "ACTIVE" || echo "NOT_ACTIVE"
          journalctl -u jett-proxy --since "1 minute ago" --no-pager | tail -30
