name: "(temporary) add fly tunnel ssh key"
on:
  workflow_dispatch:
jobs:
  addkey:
    runs-on: [self-hosted, oracle]
    timeout-minutes: 5
    steps:
      - name: Add Fly tunnel public key to ubuntu user
        run: |
          set -x
          PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDpEU1aiGqvTUO/F8u0dIHgzeEd05lel6bCCKtVZtAHG root@185777d4a263d8"
          sudo -u ubuntu mkdir -p /home/ubuntu/.ssh
          sudo -u ubuntu chmod 700 /home/ubuntu/.ssh
          echo "$PUBKEY" | sudo -u ubuntu tee -a /home/ubuntu/.ssh/authorized_keys > /dev/null
          sudo -u ubuntu chmod 600 /home/ubuntu/.ssh/authorized_keys
          sudo -u ubuntu sort -u /home/ubuntu/.ssh/authorized_keys -o /home/ubuntu/.ssh/authorized_keys
          echo "key added"
